name: Build & Deploy Docker Image

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_scan_deploy:
    name: build docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: go test ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Login to docker hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker Engine
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          push: false
          load: true
          tags: testenv:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          platforms: linux/amd64

      - name: Run Trivy vulnerability scanner - Non Blocking
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          image-ref: testenv:${{ github.run_id }}
          format: "table"
          scanners: "vuln"
          exit-code: 0 # Non blocking

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          image-ref: testenv:${{ github.run_id }}
          format: "table"
          scanners: "vuln"
          exit-code: 1 # Blocking
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"

      - name: Generate Trivy SARIF report
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        if: always()
        with:
          image-ref: testenv:${{ github.run_id }}
          format: "sarif"
          scanners: "vuln"
          exit-code: 0
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@5c8a8a642e79153f5d047b10ec1cba1d1cc65699
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tinegagideon/testenv:latest
            tinegagideon/testenv:sha-${{ github.sha }}
            tinegagideon/testenv:run-${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          platforms: linux/amd64,linux/arm64